### ISSUE TITLE
pom.xml should not contain repositories section

### ISSUE THREAD

**Issue by vsalbaba** [rh-messaging/artemis-wildfly-integration#27]
According to checks for EAP 8.0.0.Alpha-redhat-20210910, there should be no `<repositories>` section in `pom.xml`

See [relevant jenkins test run](https://master-jenkins-csb-eap-qe.apps.ocp4.prod.psi.redhat.com/job/eap-8.x-maven-repository-check-poms-for-repositories-definition/654)

Relates to [JBEAP-10177](https://issues.redhat.com/browse/JBEAP-10177)

Is the `<repositories>` section necessary here?

**Comment by ehsavoie** [comment]
https://github.com/rh-messaging/artemis-wildfly-integration/pull/29 fixes it
